{% set name = "grakel-dev" %}
{% set version = "0.1a5" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  path: ../GraKeL

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools
    - pytest
    - numpy >=1.14.0
    - scikit-learn >=0.19.0
    - scipy >=1.0.1
    - cython >=0.27.3
    - future >=0.16.0
    - six >=1.11.0
    - cvxopt >=1.2.0
  run:
    - python
    - pytest
    - numpy >=1.14.0
    - scikit-learn >=0.19.0
    - scipy >=1.0.1
    - cython >=0.27.3
    - future >=0.16.0
    - six >=1.11.0
    - cvxopt >=1.2.0
  build:
    - {{ compiler('cxx') }}

test:
  imports:
    - grakel
    - grakel.datasets
    - grakel.kernels
    - grakel.kernels._c_functions
    - grakel.kernels._isomorphism
    - grakel.tests

about:
  home: https://github.com/ysig/GraKeL
  license: BSD-3-Clause
  license_family: BSD
  license_file: ''
  summary: A scikit-learn compatible library for graph kernels.
  description: "For more info, please visit the documenantion or the github-page."
  doc_url: 'https://ysig.github.io/GraKeL/dev/'

extra:
  recipe-maintainers: 'Ioannis Siglidis'
