name: Tests

on:
  # Allow to manually trigger through github API
  workflow_dispatch:

  # Triggers with push to master
  push:
    branches:
      - master

  # Triggers with push to a pr aimed at master
  pull_request:
    branches:
      - master

  schedule:
    # https://crontab.guru/#42_2_3_*_*
    # "At 02:42 on day-of-month 3"
    # Put it at this odd time to reduce competing with load spikes on github action servers
    - cron: '42 2 3 * *'

env:

  import-package-name: grakel
  test-dir: grakel/tests
  codecov-py: "3.9"
  codecov-args: >-
    --cov=grakel
    --cov-report=xml

jobs:

  # General unit tests
  source-test:
    name: ${{ matrix.py }}-${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash # Default to using bash on all

    strategy:
      fail-fast: false
      matrix:
        py: ["3.9", "3.10", "3.11", "3.12"]
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]

    steps:
    - name: Checkout
      uses: actions/checkout@v7

    - name: Setup Python
      uses: actions/setup-python@v7
      with:
        python-version: ${{ matrix.py }}

    - name: Install uv
      uses: astral-sh/setup-uv@v9

    - name: Install ${{ env.import-package-name }}
      run: |
        # escape for cvxopt
        if [[ "${{ matrix.py }}" == "3.12" ]];then
          uv sync --locked --extra test
        else
          uv sync --locked --all-extras
        fi

    - name: Tests
      run: |
        uv run python -m pytest

  # Testing with codecov coverage uploaded
  codecov-test:
    name: codecov-test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v7

    - name: Setup Python
      uses: actions/setup-python@v7
      with:
        python-version: ${{ env.codecov-py }}

    - name: Install uv
      uses: astral-sh/setup-uv@v9

    - name: Install ${{ env.import-package-name }}
      run: |
        uv sync --locked --all-extras

    - name: Tests
      run: |
        uv run python -m pytest ${{ env.codecov-args }} ${{ env.test-dir }}

    - name: Upload coverage
      uses: codecov/codecov-action@v7
      # Only upload coverage when it's **not** a scheduled test run
      if: ${{ ! github.event.schedule }}
      with:
        verbose: true
